# .github/workflows/dbt-ci.yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # dbt-build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'

  #     - name: Install dbt
  #       run: pip install dbt-core==1.6.0 dbt-postgres==1.6.0

  #     - name: Configure dbt profile
  #       run: |
  #         mkdir -p ~/.dbt
  #         cat > ~/.dbt/profiles.yml <<EOF
  #         jornada_dw:
  #           target: prod
  #           outputs:
  #             prod:
  #               type: postgres
  #               threads: 4
  #               host: ${{ secrets.RAILWAY_DB_HOST }}
  #               user: ${{ secrets.RAILWAY_DB_USER }}
  #               pass: ${{ secrets.RAILWAY_DB_PASS }}
  #               port: ${{ secrets.RAILWAY_DB_PORT }}
  #               dbname: ${{ secrets.RAILWAY_DB_NAME }}
  #               schema: public
  #         EOF

  #     - name: dbt deps
  #       working-directory: ./data_warehouse/jornada_dw
  #       run: dbt deps --profiles-dir ~/.dbt


  #     - name: dbt build
  #       working-directory: ./data_warehouse/jornada_dw
  #       run: dbt build --profiles-dir ~/.dbt

  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install sqlfluff
        run: pip install sqlfluff sqlfluff-templater-dbt

      - name: Configure dbt profile for lint
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          jornada_dw:
            target: prod
            outputs:
              prod:
                type: postgres
                threads: 4
                host: ${{ secrets.RAILWAY_DB_HOST }}
                user: ${{ secrets.RAILWAY_DB_USER }}
                pass: ${{ secrets.RAILWAY_DB_PASS }}
                port: ${{ secrets.RAILWAY_DB_PORT }}
                dbname: ${{ secrets.RAILWAY_DB_NAME }}
                schema: public
          EOF

      - name: Run SQLFluff lint
        working-directory: ./data_warehouse/jornada_dw
        run: sqlfluff lint models/ --dialect postgres --rules LT01,LT12



